# Generated by Django 5.2.1 on 2025-05-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
